### PR TITLE
Update source code with c++11, python 2/3, and Qt5.6 to Qt5.11 compatibility for Ubuntu 19.10 

### PR DESCRIPTION
**Pull request by sildeag**
Linux only

All features work except `project_file.py`.   Some more current fixes to `DEFINES` require `wscript`, `src/wscript`, and `src/bindings/wscript` changed on April 2nd.       

Build with `--with-cyclops` (for qt4) works as before. 

Testing `--with-cyclops --with-gaia-qt5`, more work required, debug messages do not work in same way as qt4.  Also, checking out memory leaks.

Dependencies:
` ` `  Qt >= 4.5`
` ` `  libYAML >= 0.1.1`
` ` `  Python >= 2.4`
` ` `  SWIG != 3.0.8`
` ` `  waf >= 1.9`
` ` `  Eigen 3.3.4 patched version (included in source)`
    

Install dependencies (Ubuntu/Debian)

    $ apt-get install build-essential libqt4-dev libyaml-dev swig python-dev pkg-config 

    ​ or for Qt5

    $ apt-get install build-essential qt5-default qtbase5-dev libyaml-dev swig python3-dev pkg-config

Note that Gaia build may fail if you are using swig 3.0.8. Install either a previous or later version.
The newest swig version is available from source (https://github.com/swig/swig).

Release Notes: Eigen 3.3.4 is provided with source code since one header file was missing from the
archive and for c++11 compatibility. Previous Eigen had too many missing header or include files for
 version certainty. `#define Vector` was replaced by `std::vector` to eliminate c++11 errors. Location of Eigen headers changed to `3rdparty/Eigen` rather than `Eigen` folder. `Waf2.0.6` is used primarily in testing because it handles Qt5 and the `moc` files required for cyclops. `libtbb-dev` can optionally be installed but the check for `tbb` has been removed from the build process because it didn't work. `Python2.7.15` and `python3.6.3` both have been tested. However, not all versions of python have been used. Python packages are located at either `/usr/local/lib/python2.7/dist-packages` or `/usr/local/lib/python3.6/dist-packages` and utilize the major and minor python version numbers. Addendum: All tabs converted to spaces

    find ./ -iname '*.h' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;

    find ./ -iname '*.cpp' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;

    find ./ -iname '*.py' -type f -exec bash -c 'expand -t 2 "$0" | sponge "$0"' {} \;

### CODE REVIEW

**Comment by sildeag** [comment]
Not sure what you are waiting for.  Gaia2lib.pro isn't used by Ubuntu or Linux so therefore does not need to be updated.   I have updated it to use latest version Qt5 but cannot test it because I don't have Darwin.  Leave it unchanged.  `wscript` has to change but has not changed in a material way to conflict with Darwin or Windows use.  It allows both Qt4 and Qt5 for Ubuntu or Linux only, and defaults to old behaviour ie. Qt4.  The configure option `--with-gaia-qt5` must be used for Qt5 to be used.  Recent changes have been made to `wscript` since `pcfile` used by `essentia` for `gaia` config check needed `PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/config` and to reflect `/usr/local/include/gaia2` as am testing `Docker` containerized app using `python3`, Qt5, `gaia`, and `essentia`.

**Comment by sildeag** [comment]
Conflicts resolved.

**Comment by sildeag** [comment]
Fixed static library references to wrong Qt version.

**Comment by sildeag** [comment]
No real conflict as `Gaia` works as before for all environments and for `linux` allows Qt5 and for those wishing to use it Qt4.
 
The difference in `Gaia2lib.pro` is this:
` `      `GAIA_QT5=1 \`

If `GAIA_QT5=0` Gaia2lib.pro should use Qt4 build kit.  `GAIA_QT5=1` means Gaia2lib.pro should use Qt5 build kit. 

In `wscript` same functionality as before except gaia works with Qt5 or Qt4 on `linux`

**Comment by alastair** [comment]
hi @sildeag 
Thanks for all the work you did on this pull request. 
We are going to look at this upgrade again this year. Sorry for taking so long to give feedback on it.
We've already made some changes independently to start upgrading some of these components. Additionally, this pull request that you made has many small commits that you made while trying different options. We would prefer to have a smaller number of commits related to a specific task. We are interested in cleaning up your contributions and getting them merged into master.

Here are some ways that we think we can improve this pull request:
 * We already merged some python3 syntax updates in https://github.com/MTG/gaia/pull/84. We should make another separate pull request for the remaining python syntax changes
 * We already moved Eigen to an external dependency so that it doesn't conflict with essentia. This change is no longer needed
 * In the title you say that there are some c++11 upgrades. Is this only the changes you made related to Eigen, or are there other changes too? If so, we should make these changes in an new pull request
 * Did you find a specific reason why qt4 was needed for some components? It is our preference to upgrade completely to qt5 and remove support for v4. If there are some tools that absolutely require qt4, we should consider removing them from gaia if they are no longer used.
 * I see you did some additional changes such as adding copyright statements to source files, and reformatting them. Thank you for these changes. We should do these as separate pull requests to make other changes easier to identify.

Thanks again for your work!

**Comment by sildeag** [comment]
I am happy to see that the suggested changes will be of some use.  I was hoping to completely eliminate any dependency on Qt but discovered that the reason why Qt4 was never abandoned was due to features no longer supported in Qt5.  I unraveled the source code for these feature and made them available for public use so that Gaia works with Qt5.  I now have Ubuntu 19.10 and upgraded Python and c++ compilers.  Since Gaia's database features were problematic in testing, I was thinking of implementing them using Postgres sql (which is public domain) but moved on to other projects due to lack of interest in my Gaia changes.

**Comment by alastair** [comment]
In AcousticBrainz we started to use [annoy](https://github.com/spotify/annoy) for nearest neighbour search and it seems to work quite well. perhaps you are interested in something like this.

I have already finished migrating the python source files to python 3 (#90), and I have some changes ready to upgrade to qt5 which I will push next week. Based on my comments in #91 we may look at removing dependencies that only work with qt4.

#88 fixes external eigen support and c++11. We no longer need eigen as a 3rd party dependency.

I only see a few changes needed now:
 * Configure swig to generate python 3 bindings
 * add copyright headers to all source files as needed
 * Fixes to tests, I believe you have some changes in this PR too?

We would appreciate your contributions to these if you're interested (each as an individual PR). Let me know which ones you're interested in working on to ensure we don't duplicate work.

Removing Qt completely is a possible future task (#31), but at the moment I think that upgrading to Qt5 is a good first step.

**Comment by sildeag** [comment]
Thanks for the update.  I am happy that Eigen will no longer be required, as I was concerned about possible Boost, OpenGL, and CUDA dependencies which complicated things.  The removal of Cyclops and Cyclops server also helps although that code is no longer Qt dependent.  I am interested in _annoy_.  I may spend time on the unit testing as creating a proper Qt Creator debug environment does interest me.

**Pull request closed without merging**
